version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wolf-backend
    environment:
      ALLOWED_ORIGINS: http://localhost:3000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: wolf-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
